version: '3.8'

services:
  # Mealie - Recipe Management
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: http://localhost:9000
    volumes:
      - mealie-data:/app/data/
    networks:
      - meal-planner

  # Meal Planner Backend
  meal-planner-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: meal-planner-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MEALIE_URL=http://mealie:9000
      - MEALIE_TOKEN=${MEALIE_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - INSTACART_ACCESS_TOKEN=${INSTACART_ACCESS_TOKEN}
      - INSTACART_RETAILER_ID=${INSTACART_RETAILER_ID}
      - INSTACART_STORE_ID=${INSTACART_STORE_ID}
    volumes:
      - ./backend/db.json:/app/db.json
    depends_on:
      - mealie
    networks:
      - meal-planner

  # Frontend
  meal-planner-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meal-planner-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - meal-planner-backend
    networks:
      - meal-planner

volumes:
  mealie-data:

networks:
  meal-planner:
    driver: bridge
